name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      -name: checkout Repository
      users: actions/checkout@v2

      -name: Setup Python
      uses: actions/setup-python@4
      with:
        python-version: '3.9.1'

      -name: Setup Python Virtual Enviorment
      run: python -m venv python3-virtualenv

      -name: Install Dependencies
      run: python3-virtualenv/bin/pip install -r requierments

      -name: Run Tests
      run: ./run_test.sh